language: android

jdk:
 - oraclejdk11

android:
  components:
    - tools
    - platform-tools
    - build-tools-33.0.1
    - android-33
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - ./gradlew clean check assemble -Dpre-dex=false

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle